; PlatformIO - STM32 Program 01: LED Blink
; Board: STM32F103C8T6 (Blue Pill)

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
upload_protocol = stlink
monitor_speed = 115200

; For ST-Link V2
debug_tool = stlink

upload_flags =
    -c
    set CPUTAPID 0x2ba01477

build_flags = 
    -D LED_BUILTIN=PC13
