; PlatformIO Project Configuration File
; Program 01: LED Blink - Dasar GPIO Output
; Platform: ESP32 DevKitC

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Build flags
build_flags = 
    -D LED_BUILTIN=2
    -D CORE_DEBUG_LEVEL=3

; Serial Monitor
monitor_filters = 
    esp32_exception_decoder
    time
