; PlatformIO Project Configuration File
; Program 04: Button Debounce dengan esp_timer
; Platform: ESP32 DevKitC

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
