; PlatformIO - STM32 Program 03: LED Breathing (Software PWM)

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
upload_protocol = stlink
monitor_speed = 115200
